import Head from "next/head";
import Banner from "@/components/Banner";
import { Header } from "@/components/Header";
import PostCard from "@/components/PostCard/Index";
import { MediumContext } from "@/context/MediumContexxt";
import { useContext } from "react";

const style = {
  postList:
    "flex flex-col gap-3 p-2 sm:grid-cols-2 md:gap-6 md:p-6 lg:grid-cols-3",
  container: "max-w-7xl flex-1",
  main: "flex justify-center",
  wrapper: "mx-auto",
};
export default function Home() {
  const { users, posts } = useContext(MediumContext);
  return (
    <>
      <Head>
        <title>Build medium app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={style.wrapper}>
        <Header />
        <Banner />
        <div className={style.main}>
          <div className={style.container}>
            <div className={style.postList}>
              {posts.map((post) => (
                <PostCard post={post} key={post.id} />
              ))}
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
