import Banner from '@/components/Banner'
import { Header } from '@/components/Header'
import PostCard from '@/components/PostCard/Index'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Build medium app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Banner/>
      <PostCard/>
    </>
  )
}
